### PR TITLE
Wally command destroy authentication 

### PR DESCRIPTION
**Pull request by crouchygt**
The destroy command did not pass along the authentication code to the server so 301 was raised by Wally.

I also updated the rvmrc to create the gemset once the file has been trusted.

Matt

### CODE REVIEW

**Comment by sthulb** [comment]
Hi! I've not forgotten about this, I'll go through your changes on Wednesday and merge them :) 

Thanks!

**Comment by netmilk** [comment]
@sthulbourn @AndrewVos Hi, this merge is still not in latest gem version. Please bump the version and `gem push` it to be available after gem install. Proof:

```
froggy:projects netmilk$ git clone git://github.com/BBC-News/wally.git
Cloning into wally...
remote: Counting objects: 1718, done.
remote: Compressing objects: 100% (662/662), done.
remote: Total 1718 (delta 1000), reused 1691 (delta 973)
Receiving objects: 100% (1718/1718), 193.24 KiB, done.
Resolving deltas: 100% (1000/1000), done.
froggy:projects netmilk$ cd wally/
froggy:wally netmilk$ git log --pretty=format:'%h' -n 1
01edb4a
froggy:wally netmilk$ git tag --contains 400fc20 | wc -l
       0
```

**Comment by AndrewVos** [comment]
@sthulbourn I think I added you on the rubygems project so you can do this?

**Comment by sthulb** [comment]
released. It should be on RubyGems now

**Pull request merged**
