### PR TITLE
client gem, hierarchical topics, markdown readme files, .nav support, etc..

### PR DESCRIPTION
**Pull request by lenny**
Hi,

I've been experimenting with Wally as an internal feature documentation server. I was looking at Relish, but I love the idea of having something simple that can be deployed internally. Wally looked great but it was missing some key features afaiwc. Anyway, I did some admittedly aggressive hacking to bring some of Relish's more essential features to Wally.
- wally-client - See: features/wally-client/\* 

I had to change the strategy for pushing content to Wally in order to support extra content like .nav and readme files. I split out the client gem primarily to lighten up the dependencies needed to talk to Wally. The new client implementation provides a command line Thor script.

```
$ bundle exec wally-client
Tasks:
  wally-client add_project NAME     # Add project
  wally-client help [TASK]          # Describe available tasks or one specific task
  wally-client push PROJECT DIR     # Push features from DIR to PROJECT
  wally-client remove_project NAME  # Remove project
```
- Hierarchical navigation - See: features/hierarchical_topic_navigation.feature
- Customizing topic navigation with .nav file - See: features/customize_topic_navigation.feature
- Markdown readme pages - See: features/readme_pages.feature

Also, some scenario related items were missing - See the new scenarios below in features/scenario_page.feature 
- Scenario: Single cell data table
- Scenario: Scenario description
- Scenario: Doc strings 

Notes:
- I dropped the parameter based authentication for now as it was getting in the way and I was thinking that authentication
  would be better off implemented using some kind of authentication keys/tokens. Including a single password in the URL didn't seem
  to offer much.
- I started a fairly crude configuration scheme that sets configuration using a yaml file. (e.g mongo_url, etc..) See config/wally.yml read by wally/application.rb
- I didn't published the wally-client gem. If you're interested in pulling, it would preferably live under the wally namespace. For now, I had been developing using the :path option in my wally/Gemfile.

For now it is at https://github.com/lenny/wally-client

-lenny

### CODE REVIEW

**Comment by sthulb** [comment]
Hi! I've not forgotten about this, I'll go through your changes on Wednesday and merge them :) 

Thanks!

**Comment by lenny** [comment]
That would be great! The one thing I wasn't sure about and that still needs work is the authentication stuff. I've been looking at Wally as something that we would set up internally as a project feature documentation server. The idea would be to include wally-client as a development dependency in our apps and push up the feature documentation automatically as part of our build process. In our environment, IP authorization would probably be the best fit but I imagine other people will have other needs. 

Anyway... Let me know if you have any trouble checking out the new features.

**Comment by lenny** [comment]
I had picked this back up from a clean clone after some time away and realized that it wasn't exactly straight forward to get things up and running as I had last left it. Missing configuration files, etc.. would just bomb out with no feedback.  Thought that might of affected you if you tried to check things out. I fixed up a few things here and in wally-client to hopefully make it pretty painless. Let me know if you're having any trouble... Of course, I feel my fork adds a lot of good stuff, but if it's too divergent, it's no big deal, just please let me know whether you still plan to merge so I know whether to continue work here or evaluate other options.

Thanks,
-lenny

**Comment by netmilk** [comment]
@sthulbourn @AndrewVos I can see lot of work here. Please do something. If I can advice, adding this project to Travis CI can help you a lot to decide wich pull request is "Good to merge" and wich not. It will prevent situation like this when you have enthusiastic contributor to your project and now after X months his contribution seems only like piece of dead code.

**Comment by AndrewVos** [comment]
Wow ten months. Probably should have looked at this sooner.

The problem with this PR is, from my point of view, it's way too large. That's probably why we have ignored it for so long.

**Comment by AndrewVos** [comment]
Ok after having another proper look, I am going to close this PR and not merge.
- There are too many features here. You should probably only go for one feature per PR, so the devs can merge in what they think is good. Another issue is that perhaps one of these features has already been written in the time it takes us to merge.
- It seems that this pull request requires that we somehow merge the code from the client gem too. A pull request should contain all the code required to not break the project. Most people will not merge something that requires a whole lot of additional work on their side.
- You removed authentication. I wrote the authentication and I know it's pretty terrible, but we needed something. Agree that something more secure would be better, but we can't just remove it now. (I may be wrong here though, and thinking about it we probably don't need authentication for 99% of use cases)

Anyway, I'm sorry this has to happen because it's so much work and it looks so well tested too. I hope my criticisms were constructive!

**Comment by netmilk** [comment]
@sthulbourn Dead code turned into wasted code. :( Your criticism is partially constructive in my opinion. Too many features are not a problem, If they don't affect existing behavior. I don't think @lenny will be willing to refactor it after 9 months into separate PR. I see all features delivered by @lenny as very, very usefull. @lenny, can you merge `wally` and `wally-client` together and add authentication secret into the wally.yml file? @sthulbourn, is this you miss there?

**Pull request closed without merging**
